steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/imposing-voyage-392509/my-app5:$COMMIT_SHA'
      - '-f'
      - Dockerfile
      - '.'
    id: Build


  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/imposing-voyage-392509/my-app5:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
          --image=gcr.io/imposing-voyage-392509/my-app5:$COMMIT_SHA \
          --platform=$_PLATFORM \
          --region=$_DEPLOY_REGION \
          --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS \
          --quiet
          # --port=8080
    id: Deploy

images:
  - 'gcr.io/imposing-voyage-392509/my-app5:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _TRIGGER_ID: 703eb55d-52fe-4440-933a-ec51c6f291f5
  _DEPLOY_REGION: us-central1
  _PLATFORM: managed
  _SERVICE_NAME: run-server123
  _LABELS: gcb-trigger-id=703eb55d-52fe-4440-933a-ec51c6f291f5


tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - plan-config-api

options:
  logging: CLOUD_LOGGING_ONLY
