steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
      - '-c'
      - | 
        terraform init

  - id: 'tf destroy'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
      - '-c'
      - | 
        terraform destroy -auto-approve

  # - id: 'gsutil copy'
  #   name: 'gcr.io/cloud-builders/gsutil'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       gsutil cp terraform.tfstate gs://imposing-voyage-392509-tfstate/

logs_bucket: imposing-voyage-392509-tfstate
