steps:
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
      - '-c'
      - | 
        terraform init
        terraform apply -auto-approve
logs_bucket: imposing-voyage-392509-tfstate